/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'beginner' : null } |
  { 'advanced' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export type DifficultySelector = { 'all' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Feedback {
  'id' : bigint,
  'status' : FeedbackStatus,
  'title' : string,
  'createdAt' : Time,
  'authorName' : [] | [string],
  'message' : string,
  'category' : FeedbackCategory,
  'authorPrincipal' : [] | [Principal],
}
export type FeedbackCategory = { 'bug' : null } |
  { 'idea' : null } |
  { 'issue' : null };
export type FeedbackStatus = { 'pending' : null } |
  { 'completed' : null };
export interface GlobalAnalytics {
  'totalQuestionsAnswered' : bigint,
  'averageAccuracy' : number,
  'totalUsers' : bigint,
  'totalSessions' : bigint,
}
export interface Language {
  'flagEmoji' : string,
  'code' : string,
  'name' : string,
  'createdAt' : Time,
  'gradientStart' : string,
  'ordering' : bigint,
  'textDirection' : TextDirection,
  'gradientEnd' : string,
}
export interface MotivationalQuote {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
}
export type TextDirection = { 'ltr' : null } |
  { 'rtl' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'joinedAt' : Time,
  'preferredLanguages' : Array<string>,
}
export interface UserProgress {
  'xp' : bigint,
  'lastPlayed' : [] | [Time],
  'totalCorrect' : bigint,
  'streak' : bigint,
  'principal' : Principal,
  'badges' : Array<string>,
  'mostPlayedGameMode' : string,
  'totalAnswered' : bigint,
  'totalGames' : bigint,
  'accuracy' : number,
}
export interface Word {
  'id' : bigint,
  'difficulty' : Difficulty,
  'languageName' : string,
  'addedAt' : Time,
  'foreign' : string,
  'examples' : Array<string>,
  'english' : string,
}
export interface _SERVICE {
  'addWord' : ActorMethod<
    [string, string, string, Difficulty, Array<string>],
    undefined
  >,
  'adminLogin' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : boolean, 'token' : string, 'error' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'bulkImportLanguages' : ActorMethod<
    [Array<[string, string, string, TextDirection, string, string, bigint]>],
    { 'count' : bigint, 'errors' : Array<string> }
  >,
  'bulkImportWords' : ActorMethod<
    [Array<Word>],
    { 'count' : bigint, 'success' : boolean }
  >,
  'createLanguage' : ActorMethod<
    [string, string, string, TextDirection, string, string, bigint],
    undefined
  >,
  'createQuote' : ActorMethod<[string], MotivationalQuote>,
  'deleteFeedback' : ActorMethod<[bigint], undefined>,
  'deleteQuote' : ActorMethod<[bigint], undefined>,
  'deleteWord' : ActorMethod<[bigint], undefined>,
  'exportWordsCSV' : ActorMethod<
    [string],
    Array<[string, string, string, string, string, string]>
  >,
  'exportWordsJSON' : ActorMethod<[string], Array<Word>>,
  'generateMathChallenge' : ActorMethod<
    [],
    { 'question' : string, 'challengeId' : string }
  >,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllLanguages' : ActorMethod<[], Array<Language>>,
  'getAllQuotes' : ActorMethod<[], Array<MotivationalQuote>>,
  'getAllQuotesPublic' : ActorMethod<[], Array<MotivationalQuote>>,
  'getAllWords' : ActorMethod<[], Array<Word>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getGlobalAnalytics' : ActorMethod<[], GlobalAnalytics>,
  'getLanguagesSorted' : ActorMethod<[], Array<Language>>,
  'getUserAnalytics' : ActorMethod<[Principal], [] | [UserProgress]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWord' : ActorMethod<[bigint], [] | [Word]>,
  'getWordsByDifficulty' : ActorMethod<
    [string, DifficultySelector],
    Array<Word>
  >,
  'getWordsCountForLanguage' : ActorMethod<[string], bigint>,
  'getWordsForLanguagePage' : ActorMethod<
    [string, bigint, bigint],
    Array<Word>
  >,
  'isAuthenticatedAdminByToken' : ActorMethod<[string], boolean>,
  'markFeedbackCompleted' : ActorMethod<[bigint], undefined>,
  'recordGameRound' : ActorMethod<[bigint, bigint, string], undefined>,
  'removeLanguage' : ActorMethod<[string], undefined>,
  'removeWordsByLanguage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialLanguages' : ActorMethod<[], undefined>,
  'submitFeedback' : ActorMethod<
    [[] | [Principal], [] | [string], FeedbackCategory, string, string],
    Feedback
  >,
  'updateLanguage' : ActorMethod<
    [string, string, string, string, TextDirection, string, string, bigint],
    undefined
  >,
  'updateLanguageOrdering' : ActorMethod<[string, bigint], undefined>,
  'updateQuote' : ActorMethod<[bigint, string], MotivationalQuote>,
  'updateWord' : ActorMethod<
    [bigint, string, string, string, Difficulty, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];