/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Language {
    flagEmoji: string;
    code: string;
    name: string;
    createdAt: Time;
    gradientStart: string;
    ordering: bigint;
    textDirection: TextDirection;
    gradientEnd: string;
}
export interface Feedback {
    id: bigint;
    status: FeedbackStatus;
    title: string;
    createdAt: Time;
    authorName?: string;
    message: string;
    category: FeedbackCategory;
    authorPrincipal?: Principal;
}
export interface UserProgress {
    xp: bigint;
    lastPlayed?: Time;
    totalCorrect: bigint;
    streak: bigint;
    principal: Principal;
    badges: Array<string>;
    mostPlayedGameMode: string;
    totalAnswered: bigint;
    totalGames: bigint;
    accuracy: number;
}
export interface GlobalAnalytics {
    totalQuestionsAnswered: bigint;
    averageAccuracy: number;
    totalUsers: bigint;
    totalSessions: bigint;
}
export interface Word {
    id: bigint;
    difficulty: Difficulty;
    languageName: string;
    addedAt: Time;
    foreign: string;
    examples: Array<string>;
    english: string;
}
export interface UserProfile {
    name: string;
    joinedAt: Time;
    preferredLanguages: Array<string>;
}
export interface MotivationalQuote {
    id: bigint;
    createdAt: Time;
    text: string;
}
export enum Difficulty {
    beginner = "beginner",
    advanced = "advanced",
    hard = "hard",
    medium = "medium"
}
export enum DifficultySelector {
    all = "all",
    beginner = "beginner",
    advanced = "advanced",
    hard = "hard",
    medium = "medium"
}
export enum FeedbackCategory {
    bug = "bug",
    idea = "idea",
    issue = "issue"
}
export enum FeedbackStatus {
    pending = "pending",
    completed = "completed"
}
export enum TextDirection {
    ltr = "ltr",
    rtl = "rtl"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addWord(english: string, foreign: string, language: string, difficulty: Difficulty, examples: Array<string>): Promise<void>;
    adminLogin(username: string, password: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportLanguages(languageRows: Array<[string, string, string, TextDirection, string, string, bigint]>): Promise<{
        count: bigint;
        errors: Array<string>;
    }>;
    bulkImportWords(wordsToImport: Array<Word>): Promise<{
        count: bigint;
        success: boolean;
    }>;
    createLanguage(name: string, code: string, flag: string, direction: TextDirection, startColor: string, endColor: string, ordering: bigint): Promise<void>;
    createQuote(text: string): Promise<MotivationalQuote>;
    deleteFeedback(id: bigint): Promise<void>;
    deleteQuote(id: bigint): Promise<void>;
    deleteWord(id: bigint): Promise<void>;
    exportWordsCSV(language: string): Promise<Array<[string, string, string, string, string, string]>>;
    exportWordsJSON(language: string): Promise<Array<Word>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllLanguages(): Promise<Array<Language>>;
    getAllQuotes(): Promise<Array<MotivationalQuote>>;
    getAllQuotesPublic(): Promise<Array<MotivationalQuote>>;
    getAllWords(): Promise<Array<Word>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGlobalAnalytics(): Promise<GlobalAnalytics>;
    getLanguagesSorted(): Promise<Array<Language>>;
    getUserAnalytics(principal: Principal): Promise<UserProgress | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWord(id: bigint): Promise<Word | null>;
    getWordsByDifficulty(language: string, difficultySelector: DifficultySelector): Promise<Array<Word>>;
    getWordsCountForLanguage(language: string): Promise<bigint>;
    getWordsForLanguagePage(language: string, offset: bigint, limit: bigint): Promise<Array<Word>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markFeedbackCompleted(id: bigint): Promise<void>;
    recordGameRound(correctAnswers: bigint, totalQuestions: bigint, gameMode: string): Promise<void>;
    removeLanguage(language: string): Promise<void>;
    removeWordsByLanguage(language: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedInitialLanguages(): Promise<void>;
    submitFeedback(authorPrincipal: Principal | null, authorName: string | null, category: FeedbackCategory, title: string, message: string): Promise<Feedback>;
    updateLanguage(languageName: string, newName: string, newCode: string, newFlag: string, newDirection: TextDirection, newGradientStart: string, newGradientEnd: string, newOrdering: bigint): Promise<void>;
    updateLanguageOrdering(languageName: string, newOrdering: bigint): Promise<void>;
    updateQuote(id: bigint, text: string): Promise<MotivationalQuote>;
    updateWord(id: bigint, english: string, foreign: string, language: string, difficulty: Difficulty, examples: Array<string>): Promise<void>;
}
import type { Difficulty as _Difficulty, DifficultySelector as _DifficultySelector, Feedback as _Feedback, FeedbackCategory as _FeedbackCategory, FeedbackStatus as _FeedbackStatus, Language as _Language, TextDirection as _TextDirection, Time as _Time, UserProfile as _UserProfile, UserProgress as _UserProgress, UserRole as _UserRole, Word as _Word } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWord(arg0: string, arg1: string, arg2: string, arg3: Difficulty, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWord(arg0, arg1, arg2, to_candid_Difficulty_n1(this.uploadFile, this.downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWord(arg0, arg1, arg2, to_candid_Difficulty_n1(this.uploadFile, this.downloadFile, arg3), arg4);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async bulkImportLanguages(arg0: Array<[string, string, string, TextDirection, string, string, bigint]>): Promise<{
        count: bigint;
        errors: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportLanguages(to_candid_vec_n5(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportLanguages(to_candid_vec_n5(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async bulkImportWords(arg0: Array<Word>): Promise<{
        count: bigint;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportWords(to_candid_vec_n9(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportWords(to_candid_vec_n9(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createLanguage(arg0: string, arg1: string, arg2: string, arg3: TextDirection, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLanguage(arg0, arg1, arg2, to_candid_TextDirection_n7(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLanguage(arg0, arg1, arg2, to_candid_TextDirection_n7(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createQuote(arg0: string): Promise<MotivationalQuote> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuote(arg0);
            return result;
        }
    }
    async deleteFeedback(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedback(arg0);
            return result;
        }
    }
    async deleteQuote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuote(arg0);
            return result;
        }
    }
    async deleteWord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWord(arg0);
            return result;
        }
    }
    async exportWordsCSV(arg0: string): Promise<Array<[string, string, string, string, string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportWordsCSV(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportWordsCSV(arg0);
            return result;
        }
    }
    async exportWordsJSON(arg0: string): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportWordsJSON(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportWordsJSON(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllLanguages(): Promise<Array<Language>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLanguages();
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLanguages();
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllQuotes(): Promise<Array<MotivationalQuote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotes();
            return result;
        }
    }
    async getAllQuotesPublic(): Promise<Array<MotivationalQuote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotesPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotesPublic();
            return result;
        }
    }
    async getAllWords(): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWords();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWords();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGlobalAnalytics(): Promise<GlobalAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalAnalytics();
            return result;
        }
    }
    async getLanguagesSorted(): Promise<Array<Language>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLanguagesSorted();
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLanguagesSorted();
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserAnalytics(arg0: Principal): Promise<UserProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAnalytics(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAnalytics(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWord(arg0: bigint): Promise<Word | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWord(arg0);
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWord(arg0);
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWordsByDifficulty(arg0: string, arg1: DifficultySelector): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordsByDifficulty(arg0, to_candid_DifficultySelector_n39(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordsByDifficulty(arg0, to_candid_DifficultySelector_n39(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWordsCountForLanguage(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordsCountForLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordsCountForLanguage(arg0);
            return result;
        }
    }
    async getWordsForLanguagePage(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordsForLanguagePage(arg0, arg1, arg2);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordsForLanguagePage(arg0, arg1, arg2);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markFeedbackCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFeedbackCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFeedbackCompleted(arg0);
            return result;
        }
    }
    async recordGameRound(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameRound(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameRound(arg0, arg1, arg2);
            return result;
        }
    }
    async removeLanguage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLanguage(arg0);
            return result;
        }
    }
    async removeWordsByLanguage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWordsByLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWordsByLanguage(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedInitialLanguages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedInitialLanguages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedInitialLanguages();
            return result;
        }
    }
    async submitFeedback(arg0: Principal | null, arg1: string | null, arg2: FeedbackCategory, arg3: string, arg4: string): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(to_candid_opt_n41(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n42(this.uploadFile, this.downloadFile, arg1), to_candid_FeedbackCategory_n43(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
                return from_candid_Feedback_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(to_candid_opt_n41(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n42(this.uploadFile, this.downloadFile, arg1), to_candid_FeedbackCategory_n43(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
            return from_candid_Feedback_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateLanguage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: TextDirection, arg5: string, arg6: string, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLanguage(arg0, arg1, arg2, arg3, to_candid_TextDirection_n7(this.uploadFile, this.downloadFile, arg4), arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLanguage(arg0, arg1, arg2, arg3, to_candid_TextDirection_n7(this.uploadFile, this.downloadFile, arg4), arg5, arg6, arg7);
            return result;
        }
    }
    async updateLanguageOrdering(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLanguageOrdering(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLanguageOrdering(arg0, arg1);
            return result;
        }
    }
    async updateQuote(arg0: bigint, arg1: string): Promise<MotivationalQuote> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuote(arg0, arg1);
            return result;
        }
    }
    async updateWord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Difficulty, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWord(arg0, arg1, arg2, arg3, to_candid_Difficulty_n1(this.uploadFile, this.downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWord(arg0, arg1, arg2, arg3, to_candid_Difficulty_n1(this.uploadFile, this.downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_Difficulty_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n16(uploadFile, downloadFile, value);
}
function from_candid_FeedbackCategory_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackCategory): FeedbackCategory {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
function from_candid_FeedbackStatus_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackStatus): FeedbackStatus {
    return from_candid_variant_n21(uploadFile, downloadFile, value);
}
function from_candid_Feedback_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n19(uploadFile, downloadFile, value);
}
function from_candid_Language_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_record_n28(uploadFile, downloadFile, value);
}
function from_candid_TextDirection_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextDirection): TextDirection {
    return from_candid_variant_n30(uploadFile, downloadFile, value);
}
function from_candid_UserProgress_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n36(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(uploadFile, downloadFile, value);
}
function from_candid_Word_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Word): Word {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgress]): UserProgress | null {
    return value.length === 0 ? null : from_candid_UserProgress_n35(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Word]): Word | null {
    return value.length === 0 ? null : from_candid_Word_n13(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: _Difficulty;
    languageName: string;
    addedAt: _Time;
    foreign: string;
    examples: Array<string>;
    english: string;
}): {
    id: bigint;
    difficulty: Difficulty;
    languageName: string;
    addedAt: Time;
    foreign: string;
    examples: Array<string>;
    english: string;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n15(uploadFile, downloadFile, value.difficulty),
        languageName: value.languageName,
        addedAt: value.addedAt,
        foreign: value.foreign,
        examples: value.examples,
        english: value.english
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FeedbackStatus;
    title: string;
    createdAt: _Time;
    authorName: [] | [string];
    message: string;
    category: _FeedbackCategory;
    authorPrincipal: [] | [Principal];
}): {
    id: bigint;
    status: FeedbackStatus;
    title: string;
    createdAt: Time;
    authorName?: string;
    message: string;
    category: FeedbackCategory;
    authorPrincipal?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_FeedbackStatus_n20(uploadFile, downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        authorName: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.authorName)),
        message: value.message,
        category: from_candid_FeedbackCategory_n23(uploadFile, downloadFile, value.category),
        authorPrincipal: record_opt_to_undefined(from_candid_opt_n25(uploadFile, downloadFile, value.authorPrincipal))
    };
}
function from_candid_record_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flagEmoji: string;
    code: string;
    name: string;
    createdAt: _Time;
    gradientStart: string;
    ordering: bigint;
    textDirection: _TextDirection;
    gradientEnd: string;
}): {
    flagEmoji: string;
    code: string;
    name: string;
    createdAt: Time;
    gradientStart: string;
    ordering: bigint;
    textDirection: TextDirection;
    gradientEnd: string;
} {
    return {
        flagEmoji: value.flagEmoji,
        code: value.code,
        name: value.name,
        createdAt: value.createdAt,
        gradientStart: value.gradientStart,
        ordering: value.ordering,
        textDirection: from_candid_TextDirection_n29(uploadFile, downloadFile, value.textDirection),
        gradientEnd: value.gradientEnd
    };
}
function from_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    lastPlayed: [] | [_Time];
    totalCorrect: bigint;
    streak: bigint;
    principal: Principal;
    badges: Array<string>;
    mostPlayedGameMode: string;
    totalAnswered: bigint;
    totalGames: bigint;
    accuracy: number;
}): {
    xp: bigint;
    lastPlayed?: Time;
    totalCorrect: bigint;
    streak: bigint;
    principal: Principal;
    badges: Array<string>;
    mostPlayedGameMode: string;
    totalAnswered: bigint;
    totalGames: bigint;
    accuracy: number;
} {
    return {
        xp: value.xp,
        lastPlayed: record_opt_to_undefined(from_candid_opt_n37(uploadFile, downloadFile, value.lastPlayed)),
        totalCorrect: value.totalCorrect,
        streak: value.streak,
        principal: value.principal,
        badges: value.badges,
        mostPlayedGameMode: value.mostPlayedGameMode,
        totalAnswered: value.totalAnswered,
        totalGames: value.totalGames,
        accuracy: value.accuracy
    };
}
function from_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    beginner: null;
} | {
    advanced: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): FeedbackStatus {
    return "pending" in value ? FeedbackStatus.pending : "completed" in value ? FeedbackStatus.completed : value;
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bug: null;
} | {
    idea: null;
} | {
    issue: null;
}): FeedbackCategory {
    return "bug" in value ? FeedbackCategory.bug : "idea" in value ? FeedbackCategory.idea : "issue" in value ? FeedbackCategory.issue : value;
}
function from_candid_variant_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ltr: null;
} | {
    rtl: null;
}): TextDirection {
    return "ltr" in value ? TextDirection.ltr : "rtl" in value ? TextDirection.rtl : value;
}
function from_candid_variant_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Word>): Array<Word> {
    return value.map((x)=>from_candid_Word_n13(uploadFile, downloadFile, x));
}
function from_candid_vec_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n18(uploadFile, downloadFile, x));
}
function from_candid_vec_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Language>): Array<Language> {
    return value.map((x)=>from_candid_Language_n27(uploadFile, downloadFile, x));
}
function to_candid_DifficultySelector_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultySelector): _DifficultySelector {
    return to_candid_variant_n40(uploadFile, downloadFile, value);
}
function to_candid_Difficulty_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_FeedbackCategory_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackCategory): _FeedbackCategory {
    return to_candid_variant_n44(uploadFile, downloadFile, value);
}
function to_candid_TextDirection_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextDirection): _TextDirection {
    return to_candid_variant_n8(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_Word_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Word): _Word {
    return to_candid_record_n11(uploadFile, downloadFile, value);
}
function to_candid_opt_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: Difficulty;
    languageName: string;
    addedAt: Time;
    foreign: string;
    examples: Array<string>;
    english: string;
}): {
    id: bigint;
    difficulty: _Difficulty;
    languageName: string;
    addedAt: _Time;
    foreign: string;
    examples: Array<string>;
    english: string;
} {
    return {
        id: value.id,
        difficulty: to_candid_Difficulty_n1(uploadFile, downloadFile, value.difficulty),
        languageName: value.languageName,
        addedAt: value.addedAt,
        foreign: value.foreign,
        examples: value.examples,
        english: value.english
    };
}
function to_candid_tuple_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, string, string, TextDirection, string, string, bigint]): [string, string, string, _TextDirection, string, string, bigint] {
    return [
        value[0],
        value[1],
        value[2],
        to_candid_TextDirection_n7(uploadFile, downloadFile, value[3]),
        value[4],
        value[5],
        value[6]
    ];
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    beginner: null;
} | {
    advanced: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.beginner ? {
        beginner: null
    } : value == Difficulty.advanced ? {
        advanced: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultySelector): {
    all: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == DifficultySelector.all ? {
        all: null
    } : value == DifficultySelector.beginner ? {
        beginner: null
    } : value == DifficultySelector.advanced ? {
        advanced: null
    } : value == DifficultySelector.hard ? {
        hard: null
    } : value == DifficultySelector.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackCategory): {
    bug: null;
} | {
    idea: null;
} | {
    issue: null;
} {
    return value == FeedbackCategory.bug ? {
        bug: null
    } : value == FeedbackCategory.idea ? {
        idea: null
    } : value == FeedbackCategory.issue ? {
        issue: null
    } : value;
}
function to_candid_variant_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextDirection): {
    ltr: null;
} | {
    rtl: null;
} {
    return value == TextDirection.ltr ? {
        ltr: null
    } : value == TextDirection.rtl ? {
        rtl: null
    } : value;
}
function to_candid_vec_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, string, string, TextDirection, string, string, bigint]>): Array<[string, string, string, _TextDirection, string, string, bigint]> {
    return value.map((x)=>to_candid_tuple_n6(uploadFile, downloadFile, x));
}
function to_candid_vec_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Word>): Array<_Word> {
    return value.map((x)=>to_candid_Word_n10(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
