/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TextDirection = IDL.Variant({
  'ltr' : IDL.Null,
  'rtl' : IDL.Null,
});
export const Time = IDL.Int;
export const Word = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : Difficulty,
  'languageName' : IDL.Text,
  'addedAt' : Time,
  'foreign' : IDL.Text,
  'examples' : IDL.Vec(IDL.Text),
  'english' : IDL.Text,
});
export const MotivationalQuote = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
});
export const FeedbackStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const FeedbackCategory = IDL.Variant({
  'bug' : IDL.Null,
  'idea' : IDL.Null,
  'issue' : IDL.Null,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'status' : FeedbackStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'category' : FeedbackCategory,
  'authorPrincipal' : IDL.Opt(IDL.Principal),
});
export const Language = IDL.Record({
  'flagEmoji' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'gradientStart' : IDL.Text,
  'ordering' : IDL.Nat,
  'textDirection' : TextDirection,
  'gradientEnd' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : Time,
  'preferredLanguages' : IDL.Vec(IDL.Text),
});
export const GlobalAnalytics = IDL.Record({
  'totalQuestionsAnswered' : IDL.Nat,
  'averageAccuracy' : IDL.Float64,
  'totalUsers' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const UserProgress = IDL.Record({
  'xp' : IDL.Nat,
  'lastPlayed' : IDL.Opt(Time),
  'totalCorrect' : IDL.Nat,
  'streak' : IDL.Nat,
  'principal' : IDL.Principal,
  'badges' : IDL.Vec(IDL.Text),
  'mostPlayedGameMode' : IDL.Text,
  'totalAnswered' : IDL.Nat,
  'totalGames' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const DifficultySelector = IDL.Variant({
  'all' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});

export const idlService = IDL.Service({
  'addWord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportLanguages' : IDL.Func(
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Text,
            IDL.Text,
            TextDirection,
            IDL.Text,
            IDL.Text,
            IDL.Nat,
          )
        ),
      ],
      [IDL.Record({ 'count' : IDL.Nat, 'errors' : IDL.Vec(IDL.Text) })],
      [],
    ),
  'bulkImportWords' : IDL.Func(
      [IDL.Vec(Word)],
      [IDL.Record({ 'count' : IDL.Nat, 'success' : IDL.Bool })],
      [],
    ),
  'createLanguage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TextDirection,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createQuote' : IDL.Func([IDL.Text], [MotivationalQuote], []),
  'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
  'deleteQuote' : IDL.Func([IDL.Nat], [], []),
  'deleteWord' : IDL.Func([IDL.Nat], [], []),
  'exportWordsCSV' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text)
        ),
      ],
      ['query'],
    ),
  'exportWordsJSON' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(MotivationalQuote)], ['query']),
  'getAllQuotesPublic' : IDL.Func([], [IDL.Vec(MotivationalQuote)], ['query']),
  'getAllWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalAnalytics' : IDL.Func([], [GlobalAnalytics], ['query']),
  'getLanguagesSorted' : IDL.Func([], [IDL.Vec(Language)], ['query']),
  'getUserAnalytics' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProgress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWord' : IDL.Func([IDL.Nat], [IDL.Opt(Word)], ['query']),
  'getWordsByDifficulty' : IDL.Func(
      [IDL.Text, DifficultySelector],
      [IDL.Vec(Word)],
      ['query'],
    ),
  'getWordsCountForLanguage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getWordsForLanguagePage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Word)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markFeedbackCompleted' : IDL.Func([IDL.Nat], [], []),
  'recordGameRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'removeLanguage' : IDL.Func([IDL.Text], [], []),
  'removeWordsByLanguage' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialLanguages' : IDL.Func([], [], []),
  'submitFeedback' : IDL.Func(
      [
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Text),
        FeedbackCategory,
        IDL.Text,
        IDL.Text,
      ],
      [Feedback],
      [],
    ),
  'updateLanguage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TextDirection,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateLanguageOrdering' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateQuote' : IDL.Func([IDL.Nat, IDL.Text], [MotivationalQuote], []),
  'updateWord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TextDirection = IDL.Variant({ 'ltr' : IDL.Null, 'rtl' : IDL.Null });
  const Time = IDL.Int;
  const Word = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : Difficulty,
    'languageName' : IDL.Text,
    'addedAt' : Time,
    'foreign' : IDL.Text,
    'examples' : IDL.Vec(IDL.Text),
    'english' : IDL.Text,
  });
  const MotivationalQuote = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  const FeedbackStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const FeedbackCategory = IDL.Variant({
    'bug' : IDL.Null,
    'idea' : IDL.Null,
    'issue' : IDL.Null,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'status' : FeedbackStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'category' : FeedbackCategory,
    'authorPrincipal' : IDL.Opt(IDL.Principal),
  });
  const Language = IDL.Record({
    'flagEmoji' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'gradientStart' : IDL.Text,
    'ordering' : IDL.Nat,
    'textDirection' : TextDirection,
    'gradientEnd' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedAt' : Time,
    'preferredLanguages' : IDL.Vec(IDL.Text),
  });
  const GlobalAnalytics = IDL.Record({
    'totalQuestionsAnswered' : IDL.Nat,
    'averageAccuracy' : IDL.Float64,
    'totalUsers' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const UserProgress = IDL.Record({
    'xp' : IDL.Nat,
    'lastPlayed' : IDL.Opt(Time),
    'totalCorrect' : IDL.Nat,
    'streak' : IDL.Nat,
    'principal' : IDL.Principal,
    'badges' : IDL.Vec(IDL.Text),
    'mostPlayedGameMode' : IDL.Text,
    'totalAnswered' : IDL.Nat,
    'totalGames' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const DifficultySelector = IDL.Variant({
    'all' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  
  return IDL.Service({
    'addWord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportLanguages' : IDL.Func(
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Text,
              TextDirection,
              IDL.Text,
              IDL.Text,
              IDL.Nat,
            )
          ),
        ],
        [IDL.Record({ 'count' : IDL.Nat, 'errors' : IDL.Vec(IDL.Text) })],
        [],
      ),
    'bulkImportWords' : IDL.Func(
        [IDL.Vec(Word)],
        [IDL.Record({ 'count' : IDL.Nat, 'success' : IDL.Bool })],
        [],
      ),
    'createLanguage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TextDirection,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createQuote' : IDL.Func([IDL.Text], [MotivationalQuote], []),
    'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
    'deleteQuote' : IDL.Func([IDL.Nat], [], []),
    'deleteWord' : IDL.Func([IDL.Nat], [], []),
    'exportWordsCSV' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Text,
              IDL.Text,
              IDL.Text,
              IDL.Text,
            )
          ),
        ],
        ['query'],
      ),
    'exportWordsJSON' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(MotivationalQuote)], ['query']),
    'getAllQuotesPublic' : IDL.Func(
        [],
        [IDL.Vec(MotivationalQuote)],
        ['query'],
      ),
    'getAllWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalAnalytics' : IDL.Func([], [GlobalAnalytics], ['query']),
    'getLanguagesSorted' : IDL.Func([], [IDL.Vec(Language)], ['query']),
    'getUserAnalytics' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProgress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWord' : IDL.Func([IDL.Nat], [IDL.Opt(Word)], ['query']),
    'getWordsByDifficulty' : IDL.Func(
        [IDL.Text, DifficultySelector],
        [IDL.Vec(Word)],
        ['query'],
      ),
    'getWordsCountForLanguage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getWordsForLanguagePage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Word)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markFeedbackCompleted' : IDL.Func([IDL.Nat], [], []),
    'recordGameRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'removeLanguage' : IDL.Func([IDL.Text], [], []),
    'removeWordsByLanguage' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialLanguages' : IDL.Func([], [], []),
    'submitFeedback' : IDL.Func(
        [
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Text),
          FeedbackCategory,
          IDL.Text,
          IDL.Text,
        ],
        [Feedback],
        [],
      ),
    'updateLanguage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TextDirection,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateLanguageOrdering' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateQuote' : IDL.Func([IDL.Nat, IDL.Text], [MotivationalQuote], []),
    'updateWord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };